spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        # Route for user-service
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**


        # Route for hotel-service
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**


        # Route for rating-service
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8084


# OKTA configuration for API Gateway

okta:
  oauth2:
    issuer: https://dev-63105764.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaks4yj5jqURFFrn5d7
    client-secret: H1uf2ZSZqwp_ogTddpGnx1_CiGoAkUOuh2rGetmJfUtD-6mfpen84aRuSSu5cQ3w
    scope: openid, profile, email, offline_access

