server:
  port: 8761  # The port on which the Eureka server will run

spring:
  application:
    name: ServiceRegistry

eureka:
  client:
    register-with-eureka: false  # Eureka server won't register with itself
    fetch-registry: false        # Eureka server won't fetch the registry as it's the main server
  instance:
    hostname: localhost
