# Spring Boot Application Configuration in YAML format

server:
  port: 8082  # The port your service will run on

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices # Replace with your DB connection URL
    username: root  # Your MySQL username
    password: akhila  # Your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates/updates tables based on your entities
    show-sql: true  # Show SQL queries in the console

  application:
    name: hotel-service  # The name of the microservice in Eureka

  config:
    import: optional:configserver:http://localhost:8085


okta:
  oauth2:
    issuer: https://dev-63105764.okta.com/oauth2/default
    audience: api://default



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    registry-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
